using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Demo_Constructors
{
    /// <summary>
    ///     Class with the CONSTRUCTOR generated by the Language Compiler.
    ///     The constructor generated by the compiler is ALWAYS the default constructor
    /// </summary>
    class Demo1
    {

    }
}
