# This is a REST client (.http file) to test the API.


@Demo_SecuredWebApi_HostAddress = https://localhost:7204

@username=user
@password=password

@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOlsiU3VwZXJVc2VyIiwiVXNlciJdLCJleHAiOjE3NTczMjg2OTQsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcyMDQiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MjA0In0.gae21LQxNs62MHz5V0gFiMAPWXgQxlk0qz1gnabugSg

###

GET {{Demo_SecuredWebApi_HostAddress}}/api/demo/public

###


POST {{Demo_SecuredWebApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###

GET {{Demo_SecuredWebApi_HostAddress}}/api/demo/private
Authorization: Bearer {{authToken}}

###

GET {{Demo_SecuredWebApi_HostAddress}}/api/demo/private
Authorization: Bearer {{authToken}}

###


GET {{Demo_SecuredWebApi_HostAddress}}/api/demo/checkmyrole
Authorization: Bearer {{authToken}}

###
